tag = "tags"

# contidos
eqt-contido = "eqt-contidos"

# nome
eqt-franquia = "eqt-franquias"

# pelicula, serie, documental, anime
eqt-tipo = "eqt-tipos"

eqt-autor = "eqt-autores"

eqt-titulo = "eqt-titulos"
