tag = "tags"

# contidos
eqt-contido = "eqt-contidos"

# nome
eqt-franquia = "eqt-franquias"

# pelicula, serie, documental, anime
eqt-tipo = "eqt-tipos"

eqt-autor = "eqt-autores"
eqt-subtitulador = "eqt-subtituladores"

eqt-titulo = "eqt-titulos"
eqt-pais = "eqt-paises"
eqt-linguas = "eqt-linguas"

eqt-estado = "eqt-estados"
eqt-xenero = "eqt-xeneros"
eqt-certificacion = "eqt-certificacions"
